language: ruby
rvm:
  - 2.0.0-p481
before_script:
  - mysql -e 'create database IF NOT EXISTS `enpit-test_test`;'
deploy:
  provider: heroku
  api_key:
    secure: seC9FQmzGmozB+hz5bDjTHzEUatK3jInNoMLBAM1r2zRnNtX0HYnOdZ4HEc/Bf88Lov7/tJB4sAHoeec2ftuYmWAL8b2nsEjVLl/8U1vgHprzzCsD/bIer8sYVetw9V7tdGkesR1d9RK0YDZ6tvLZrsbLDHIKZkclqriOw2LWJw=
git:
  submodules: false
cache: bundler

